name: Refresh EKS FINOS Legend deployment

on:
  workflow_dispatch:
  schedule:
    # Runs everyday at 00:00. (see https://crontab.guru)
    - cron: '0 0 * * *'

jobs:
  build:
    name: Trigger Juju refresh on EKS Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Installing Dependencies
        run: |
          sudo snap install juju --classic

      #- name: Install Docker
      #  uses: docker-practice/actions-setup-docker@master

      # We need the kubeconfig and the controllers.yaml file into our environment
      # in order to login and refresh the charms.
      - name: Adding Credentials
        shell: bash
        run: |
          mkdir -p ~/.kube
          mkdir -p ~/.local/share/juju
          echo "${KUBECONFIG_B64}" | base64 -d > ~/.kube/config
          echo "${CONTROLLERS_B64}" | base64 -d > ~/.local/share/juju/controllers.yaml

          echo "${CONTROLLER_PASSWORD}" | juju login -c finos-legend -u admin
        
        env:
          KUBECONFIG_B64: "${{ secrets.KUBECONFIG_B64 }}"
          CONTROLLERS_B64: "${{ secrets.CONTROLLERS_B64 }}"
          CONTROLLER_PASSWORD: "${{ secrets.CONTROLLER_PASSWORD }}"
          
      - name: Refreshing Charms
        run: |
          
          # Controller and model names are the same, "finos-legend"
          juju switch finos-legend:finos-legend
          
          # Running juju status will show us the current revisions of the charms.
          juju status
          
          # Upgrade controller model
          juju upgrade-controller -c finos-legend

          # Upgrade the current model
          juju upgrade-model
          
          juju refresh legend-engine --channel="latest/edge"
          juju refresh legend-sdlc --channel="latest/edge"
          juju refresh legend-studio --channel="latest/edge"

          wget https://api.charmhub.io/api/v1/resources/download/charm_TBzZNfouxr5BSuBzJYfOlS8j646H0Ll7.engine-image_30
          wget https://api.charmhub.io/api/v1/resources/download/charm_4follyZ2G5M6we0qBGYdoQpkBlpuUTpU.sdlc-image_30
          wget https://api.charmhub.io/api/v1/resources/download/charm_ydBmjPqafc9RoYcAttbzpqZXvMliaXn3.studio-image_89

          juju attach-resource legend-engine name=charm_TBzZNfouxr5BSuBzJYfOlS8j646H0Ll7.engine-image_30
          juju attach-resource legend-sdlc name=charm_4follyZ2G5M6we0qBGYdoQpkBlpuUTpU.sdlc-image_30
          juju attach-resource legend-studio name=charm_ydBmjPqafc9RoYcAttbzpqZXvMliaXn3.studio-image_89
          
        
          # Running juju status will show us the current revisions of the charms.
          juju status
